# Generated by Django 3.0.2 on 2020-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordertotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
